import 'package:crm_system/src/features/dash_board/presentation/widget/projectDetailCard.dart';
import 'package:crm_system/src/features/dash_board/presentation/widget/workLoadItem.dart';
import 'package:crm_system/src/features/profile/presentation/widget/profile_vacation.dart';
import 'package:crm_system/src/utilities/colors.dart';
import 'package:crm_system/src/utilities/image_path.dart';
import 'package:flutter/material.dart';

final List<ProjectCard> mockProjects = [
  const ProjectCard(
    projectId: "PN0001265",
    projectName: "Medical App (iOS native)",
    creationDate: "Created Sep 12, 2020",
    priority: "Medium",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectAvatar3, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001266",
    projectName: "Food Delivery Service",
    creationDate: "Created Sep 12, 2020",
    priority: "Low",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001267",
    projectName: "E-commerce Platform",
    creationDate: "Created Nov 15, 2021",
    priority: "Low",
    allTasks: 50,
    activeTasks: 25,
    projectIcon: projectAvatar2, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001265",
    projectName: "Medical App (iOS native)",
    creationDate: "Created Sep 12, 2020",
    priority: "Medium",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectAvatar3, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001266",
    projectName: "Food Delivery Service",
    creationDate: "Created Sep 12, 2020",
    priority: "Low",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001267",
    projectName: "E-commerce Platform",
    creationDate: "Created Nov 15, 2021",
    priority: "Low",
    allTasks: 50,
    activeTasks: 25,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001265",
    projectName: "Medical App (iOS native)",
    creationDate: "Created Sep 12, 2020",
    priority: "Medium",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001266",
    projectName: "Food Delivery Service",
    creationDate: "Created Sep 12, 2020",
    priority: "Low",
    allTasks: 34,
    activeTasks: 13,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
  const ProjectCard(
    projectId: "PN0001267",
    projectName: "E-commerce Platform",
    creationDate: "Created Nov 15, 2021",
    priority: "Low",
    allTasks: 50,
    activeTasks: 25,
    projectIcon: projectavtar1, // Replace with your SVG path
  ),
];

final List<ProfileVacation> mockVacationList = [
  ProfileVacation(
    avatarColor: AppColors.blue,
    leaveType: "Sick Leave",
    status: "Pending",
    statusContainerColor: AppColors.yellow,
    dateRange: "Sep 13, 2020 - Sep 16, 2020",
    duration: "3d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Casual Leave",
    status: "Approved",
    statusContainerColor: AppColors.green,
    dateRange: "Oct 01, 2020 - Oct 03, 2020",
    duration: "2d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Maternity Leave",
    status: "Rejected",
    statusContainerColor: AppColors.blue,
    dateRange: "Nov 15, 2020 - Nov 30, 2020",
    duration: "15d",
  ),
  ProfileVacation(
    avatarColor: AppColors.blue,
    leaveType: "Sick Leave",
    status: "Pending",
    statusContainerColor: AppColors.yellow,
    dateRange: "Sep 13, 2020 - Sep 16, 2020",
    duration: "3d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Casual Leave",
    status: "Approved",
    statusContainerColor: AppColors.green,
    dateRange: "Oct 01, 2020 - Oct 03, 2020",
    duration: "2d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Maternity Leave",
    status: "Rejected",
    statusContainerColor: AppColors.blue,
    dateRange: "Nov 15, 2020 - Nov 30, 2020",
    duration: "15d",
  ),
  ProfileVacation(
    avatarColor: AppColors.blue,
    leaveType: "Sick Leave",
    status: "Pending",
    statusContainerColor: AppColors.yellow,
    dateRange: "Sep 13, 2020 - Sep 16, 2020",
    duration: "3d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Casual Leave",
    status: "Approved",
    statusContainerColor: AppColors.green,
    dateRange: "Oct 01, 2020 - Oct 03, 2020",
    duration: "2d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Maternity Leave",
    status: "Rejected",
    statusContainerColor: AppColors.blue,
    dateRange: "Nov 15, 2020 - Nov 30, 2020",
    duration: "15d",
  ),
  ProfileVacation(
    avatarColor: AppColors.blue,
    leaveType: "Sick Leave",
    status: "Pending",
    statusContainerColor: AppColors.yellow,
    dateRange: "Sep 13, 2020 - Sep 16, 2020",
    duration: "3d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Casual Leave",
    status: "Approved",
    statusContainerColor: AppColors.green,
    dateRange: "Oct 01, 2020 - Oct 03, 2020",
    duration: "2d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Maternity Leave",
    status: "Rejected",
    statusContainerColor: AppColors.blue,
    dateRange: "Nov 15, 2020 - Nov 30, 2020",
    duration: "15d",
  ),
  ProfileVacation(
    avatarColor: AppColors.blue,
    leaveType: "Sick Leave",
    status: "Pending",
    statusContainerColor: AppColors.yellow,
    dateRange: "Sep 13, 2020 - Sep 16, 2020",
    duration: "3d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Casual Leave",
    status: "Approved",
    statusContainerColor: AppColors.green,
    dateRange: "Oct 01, 2020 - Oct 03, 2020",
    duration: "2d",
  ),
  ProfileVacation(
    avatarColor: AppColors.yellow,
    leaveType: "Maternity Leave",
    status: "Rejected",
    statusContainerColor: AppColors.blue,
    dateRange: "Nov 15, 2020 - Nov 30, 2020",
    duration: "15d",
  ),
];

final List<WorkloadItem> mockWorkloadList = [
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.6,
    dpImage: dp2png,
    name: "Emily Carter",
    role: "Frontend Developer",
    level: "Senior",
    bgColor: Colors.green.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.6,
    dpImage: dp2png,
    name: "Emily Carter",
    role: "Frontend Developer",
    level: "Senior",
    bgColor: Colors.green.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.6,
    dpImage: dp2png,
    name: "Emily Carter",
    role: "Frontend Developer",
    level: "Senior",
    bgColor: Colors.green.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.6,
    dpImage: dp2png,
    name: "Emily Carter",
    role: "Frontend Developer",
    level: "Senior",
    bgColor: Colors.green.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
  WorkloadItem(
    progressValue: 0.3,
    dpImage: dp1png,
    name: "Shawn Stone",
    role: "UI/UX Designer",
    level: "Middle",
    bgColor: Colors.blue.shade100,
  ),
  WorkloadItem(
    progressValue: 0.6,
    dpImage: dp2png,
    name: "Emily Carter",
    role: "Frontend Developer",
    level: "Senior",
    bgColor: Colors.green.shade100,
  ),
  WorkloadItem(
    progressValue: 0.8,
    dpImage: dp3png,
    name: "Michael Ford",
    role: "Backend Developer",
    level: "Expert",
    bgColor: Colors.red.shade100,
  ),
  WorkloadItem(
    progressValue: 0.4,
    dpImage: dp2png,
    name: "Jessica Lee",
    role: "Product Manager",
    level: "Junior",
    bgColor: Colors.purple.shade100,
  ),
];
